{% set name = "scope-astr" %}
{% set version = "0.4.1b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scope_astr-{{ version }}.tar.gz
  sha256: 885fc704b9be986608ea9421789dcb296e4723ab7eb8a2b08506e2675603783e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - setuptools-scm >=8
    - setuptools-git-versioning <2
    - pip
  run:
    - python >=3.10
    - numpy
    - astropy >5.1
    - scipy
    - jax
    - exoplanet
    - tqdm
    - emcee
    - numba
    - scikit-learn >=1.3.0
    - matplotlib-base
    - pandas
    - exoplanet-core
    - pymc >=4
    - schwimmbad

test:
  imports:
    - scope
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arjunsavel/scope
  summary: Simulating high-resolution spectroscopy of exoplanet atmospheres.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arjunsavel
